import{a as m,i as u,S as p}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function y(s,r=1){const e=`https://pixabay.com/api/?key=47065428-a0220427b8b9e139f136fc7ca&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{return(await m.get(e)).data}catch(t){throw console.error("Error:",t),t}}function f(s){const r=document.querySelector(".gallery"),n=s.map(o=>`<div class="photo-card">
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${o.likes}</p>
        <p class="info-item"><b>Views:</b> ${o.views}</p>
        <p class="info-item"><b>Comments:</b> ${o.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </div>`).join("");r.insertAdjacentHTML("beforeend",n)}function h(s){u.error({title:"Error",message:s,position:"topRight"})}const b=document.querySelector("#search-form"),w=document.querySelector("#search-input"),c=document.querySelector(".loader"),d=document.querySelector(".gallery"),i=document.createElement("button");i.textContent="Load more";i.style.display="none";document.body.appendChild(i);let a=1,g="";b.addEventListener("submit",async s=>{s.preventDefault();const r=w.value.trim();if(!r){u.error({title:"Error",message:"Please enter a search term."});return}c.style.display="block",g=r,a=1;try{const n=await y(r,a);d.innerHTML="",f(n.hits),c.style.display="none",n.totalHits>a*15?i.style.display="block":i.style.display="none",new p(".gallery a").refresh(),window.scrollBy({top:d.getBoundingClientRect().top-window.innerHeight,behavior:"smooth"})}catch(n){c.style.display="none",h("An error occurred while fetching data. Please try again later."),console.error("Error fetching data: ",n)}});i.addEventListener("click",async()=>{a+=1;try{const s=await y(g,a);f(s.hits);const r=d.querySelector(".photo-card");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}s.totalHits<=a*15&&(i.style.display="none",u.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),new p(".gallery a").refresh()}catch{h("An error occurred while fetching additional data. Please try again later.")}});
//# sourceMappingURL=index.js.map
