import{a as m,i as c,S as y}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function p(s,r=1){const e=`https://pixabay.com/api/?key=47065428-a0220427b8b9e139f136fc7ca&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{return(await m.get(e)).data}catch(t){throw console.error("Error:",t),t}}function f(s){const r=document.querySelector(".gallery"),n=s.map(o=>`<div class="photo-card">
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${o.likes}</p>
        <p class="info-item"><b>Views:</b> ${o.views}</p>
        <p class="info-item"><b>Comments:</b> ${o.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </div>`).join("");r.insertAdjacentHTML("beforeend",n)}function h(s){c.error({title:"Error",message:s,position:"topRight"})}const b=document.querySelector("#search-form"),w=document.querySelector("#search-input"),l=document.querySelector(".loader"),u=document.querySelector(".gallery"),i=document.createElement("button");i.textContent="Load more";i.style.display="none";document.body.appendChild(i);let a=1,g="";b.addEventListener("submit",async s=>{s.preventDefault();const r=w.value.trim();if(!r){c.error({title:"Error",message:"Please enter a search term."});return}l.style.display="block",g=r,a=1;try{const n=await p(r,a);if(u.innerHTML="",n.hits.length===0){l.style.display="none",c.info({title:"No results",message:"Sorry, no images were found for your search.",position:"topRight"});return}f(n.hits),l.style.display="none",n.totalHits>a*15?i.style.display="block":i.style.display="none",new y(".gallery a").refresh(),window.scrollBy({top:u.getBoundingClientRect().top-window.innerHeight,behavior:"smooth"})}catch(n){l.style.display="none",h("An error occurred while fetching data. Please try again later."),console.error("Error fetching data: ",n)}});i.addEventListener("click",async()=>{a+=1;try{const s=await p(g,a);f(s.hits);const r=u.querySelector(".photo-card");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}s.totalHits<=a*15&&(i.style.display="none",c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),new y(".gallery a").refresh()}catch{h("An error occurred while fetching additional data. Please try again later.")}});
//# sourceMappingURL=index.js.map
